name: Build and Push Alpine Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: example-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Build Alpine Docker image
        run: |
          docker build \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(git rev-parse --short HEAD) \
            --build-arg IMAGE_VERSION=${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_NAME }}:latest \
            -f Dockerfile .
  
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          docker push ${{ env.IMAGE_NAME }}:latest
